theme: jekyll-theme-minimal
title: Kontakt zur ehemaligen Stupidedia-Community
description: Dein bisheriger Draht zu den Leuten der Stupidedia wurde archiviert? Bange nicht!
show_downloads: false
logo: https://web.archive.org/web/20180310213333im_/http://www.stupidedia.org/stupidedia.png
